version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - /root/html:/etc/nginx/html:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/www:/var/www/certbot:rw
      - ./data/certbot/conf:/etc/letsencrypt:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"